### ISSUE TITLE
Game status showing pending instead of cancelled

### ISSUE THREAD

**Issue by stuartrapop** [lorobert42/ft_transcendence#139]
When a game is quit game status stays pending

{
    "id": 8,
    "tournament": null,
    "tournamentRound": 0,
    "roundGame": 0,
    "player1": 3,
    "player2": 1,
    "score1": 0,
    "score2": 0,
    "player1_status": "playing",
    "player2_status": "pending",
    "game_status": "pending",
    "start_time": null
  }

**Comment by MrMobbi** [comment]
fix
