### ISSUE TITLE
todo - tranductions manquantes

### ISSUE THREAD

**Issue by maxstocklin** [lorobert42/ft_transcendence#63]
Friends view
- Pending Invites
- Add Friend
- Friend list
- "Search User..." text to fill
- "add" button

Tournament
- Round
- User

Games
- Pending games
- Game creation
- search game
- game room
- Create local game
- create tournament
- create remote game
- join / deny buttons

game rooms
- start game button
- room title

**Comment by lorobert42** [comment]
A faire aussi pour tous les messages des toasts

**Comment by stuartrapop** [comment]
Update page
